services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
  haystack_app:
    build:
      context: ./haystack_app
    ports:
      - 7777:7777
    depends_on:
      - elasticsearch