FROM --platform=$BUILDPLATFORM python:3.10 AS builder

WORKDIR /service
COPY . /service

RUN apt update
RUN apt install build-essential
RUN pip install pip --upgrade
RUN pip install -r requirements.txt

# 환경변수
ENV FLASK_APP app.py
ENV FLASK_RUN_PORT 7777
ENV FLASK_RUN_HOST 0.0.0.0

EXPOSE 7777

# 구동 명령
ENTRYPOINT ["flask", "run"]